baseURL = "https://theqajedi.in/"
title = "The QA Jedi"

theme = "coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentsuseclasses = true
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"
enableTwemoji = true
colorscheme = "auto"
##googleanalytics = ""

hideFooter = false
hideCredits = false
hideCopyright = false
since = 2020
dateformat = "January 2, 2006"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    author = "Abilash Margapuram"
    title = "The QA Jedi"
    avatarurl = "images/avatar.jpg"
    jedi = "images/qa_jedi.png"
    info = "On a quest to make the force stronger on the quality side."
    keywords = "blog,tester,qa,java"

    custom_css = ["css/custom.css", "css/syntax.css"]

[[params.social]]
name = "Blog"
icon = "fab fa-blogger-b"
weight = 1
url = "/posts"
[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
weight = 1
url = "https://www.linkedin.com/in/abilash-margapuram"
[[params.social]]
name = "Github"
icon = "fab fa-github"
weight = 1
url = "https://github.com/theqajedi"
[[params.social]]
name = "Email"
icon = "far fa-envelope"
weight = 1
url = "mailto:abilash31@yahoo.co.in"

[languages]
[languages.en]
languagename = "English"

[languages.en.menu]

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"
